### ISSUE TITLE
Feature: tagging / highlighting

### ISSUE THREAD

**Issue by jbpratt78** [jbpratt78/strims-chat-mobile#7]
- Ability to tag a user with the syntax `/tag {user} {color}`
- Ability to highlight a word with the syntax `/highlight {word}`
- Untag
- Unhighlight

(This data can be persisted) for reference #5

**Comment by aliveSurfin** [comment]
this should just be a carbon copy of the link highlighting, are we highlighting the whole message ?

**Comment by jbpratt78** [comment]
I would either like to add a simple border around the name of the given color (for tagging) or add the color bar to the far left that currently exists in chat-gui. For highlighting, this should be handle visually in the same way chat-gui does as well.

**Comment by aliveSurfin** [comment]
- [x] ignoring and hiding messages based on user or word
- [ ] tagging users with a specific colour
- [ ] differentiate highlighted word from a user mention

**Comment by jbpratt78** [comment]
Closed with edbe612
