### ISSUE TITLE
Autocomplete suggestions are not initialized until clicking on the form

### ISSUE THREAD

**Issue by jbpratt78** [jbpratt78/strims-chat-mobile#80]

**Comment by aliveSurfin** [comment]
will be fixed by storing/loading most used emotes / usernames

**Comment by jbpratt78** [comment]
@aliveSurfin so store a client's most popular words and pre-populate it with that? Currently, when clicking on the form we populate it with all of the emotes from what I remember. Is there a reason that we do not do this on start up?

**Comment by aliveSurfin** [comment]
@jbpratt78 no reason I can see, we can change to populating on startup when we load the client's popular words

**Comment by jbpratt78** [comment]
Closed with 5a77916
